name = "Secondary-Electron-Model"

version = "0.1.0"

license = "Apache License Version 2.0"
author = "Nkzono99"
maintainer = "210x218x@stu.kobe-u.ac.jp"
copyright = "Copyright 2025, Nkzono99"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

